server:
  port: 8081

spring:
  application:
    name: auth-service

  security:
    user:
      name: admin
      password: admin

  consul:
    host: localhost
    port: 8500
    discovery:
      service-name: auth-service
      register: true

jwt:
  secret: my-secret-key
  expiration: 3600000

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
